version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "20002:6379"
  db:
    image: mysql:5.7
    ports:
      - "20001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bundle exec rails server --port=3000 --binding='0.0.0.0'
    volumes:
      - .:/rails-mysql-slim
      - bundle:/usr/local/bundle
    ports:
      - "20000:3000"
    depends_on:
      - db
      - redis
    # binding.pryで止められるように
    tty: true
    stdin_open: true
volumes:
  bundle:
  db:
